### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ignissak** [dragonfire535/node-superfetch#9]
**Please describe the problem you are having in as much detail as possible**:
some unknown error occurs when I'm trying to run my project
```
/home/root/lfheroes-bot/node_modules/node-superfetch/index.js:136
        Request[method.toLowerCase()] = (url, options) => new Request({ url, method, ...options });
                                                                                     ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/root/lfheroes-bot/node_modules/hastebgen-js/index.js:1:79)
```

**Further details**:

- node-superfetch version: 0.19
- Node.js version: 6.9.0
- Operating system: ubuntu 18.04.2
- Priority this issue should have – please be realistic and elaborate if possible: HIGH

**Comment by xiaobotdev** [comment]
This is because you are using a version of Node this project doesn't support. Upgrade.
